from marshmallow import Schema, fields

class DzmlNewSchema(Schema):
    year = fields.Int()
    month = fields.Int()
    day = fields.Int()
    hour = fields.Int()
    min = fields.Int()
    sec = fields.Float()
    lon = fields.Float()
    lat = fields.Float()
    depth = fields.Int()
    mc = fields.Float()
    JingDu = fields.Str()
    WeiDu = fields.Str()
    DiMing = fields.Str()
    ZhenJiZhi = fields.Float()
    ShenDu = fields.Int()
    RiQi = fields.DateTime(allow_none=True)
    years = fields.Str()
    ZhenJiLeiXing = fields.Str()
    mag1 = fields.Str()
    DiZhenLeiXing = fields.Str()
    WeiHao = fields.Int()
    tag = fields.Int()
    Notes = fields.Str()
    OldId = fields.Str()
    UpgradeTime = fields.DateTime(allow_none=True)
