from marshmallow import Schema, fields

class InstrumentSchema(Schema):
    id = fields.Int()
    stationId = fields.Str()
    region = fields.Str()
    pointId = fields.Int()
    lat = fields.Float()
    lon = fields.Float()
    instrId = fields.Str()
    stackNo = fields.Int()
    instrcode = fields.Str()
    sampleRate = fields.Str()
    type = fields.Str()
    style = fields.Str()
    discipline = fields.Str()
    startDate = fields.DateTime(allow_none=True)
    endDate = fields.DateTime(allow_none=True)
    instrProject = fields.Str()
    dcunitCode = fields.Str()
    illeagle = fields.Str()
    registerFlag = fields.Int()
    status = fields.Int()
    created_at = fields.DateTime(allow_none=True)